eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka
  profiles:
    active: dev
server:
  port: 8761

logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml