eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka2
server:
  port: 8762
